### ISSUE TITLE
Styles are not loading, angular 9

### ISSUE THREAD

**Issue by mike9ar** [avraampiperidis/ng-fullyearcalendar#3]
![imagen](https://user-images.githubusercontent.com/22224714/81024225-2b64bb00-8e49-11ea-8458-6c9bcba8cf16.png)

Render is not correct, maybe styles are not loading. I can see year values exists in the inspector.

**Comment by mike9ar** [comment]
I did work it... the class ".tooltip" has conflict with boostrap "tooltip" style class, I edited monthly-calendar component and changed "tooltip" style class name.

**Comment by viccast** [comment]
Hi, I have the same issue, Could you help me please? What files did you change? Thank you.

**Comment by antoine-galataud** [comment]
@viccast in case you're still looking for a solution, you can edit your component's css and add following instruction:

```css
:host ::ng-deep .tooltip {
    position: relative;
    opacity: 1;
}
```

**Comment by viccast** [comment]
> @viccast in case you're still looking for a solution, you can edit your component's css and add following instruction:
> 
> ```css
> :host ::ng-deep .tooltip {
>     position: relative;
>     opacity: 1;
> }
> ```

Thank you, it works!
